### ISSUE TITLE
Plugin corrupts regex expressions during normalization

### ISSUE THREAD

**Issue by skalinets** [RedPillAnalytics/gradle-confluent#104]
**Describe the bug**
One of normalization steps [includes removing of double backslashes](https://github.com/RedPillAnalytics/gradle-confluent/blob/master/src/main/groovy/com/redpillanalytics/gradle/tasks/PipelineTask.groovy#L114). It affects regular expressions. 

**To Reproduce**
1. Create stream with regex (e.g. `REGEXP_REPLACE(date, '\\.\\d+', '')`)
2. Run `./gradlew ksql:build`
3. Check `ksql/build/pipeline/ksql-script.sql` 
4. Regex becomes `REGEXP_REPLACE(date, '.d+', '')`

**Expected behavior**
Regex expressions are not broken

**Desktop (please complete the following information):**

**Workaround**
Some regexes could be changed: `"\\."` --> `"[.]"`, `"\\d"` --> `"[0-9]"` etc.

**Comment by stewartbryson** [comment]
I've been wanting to rewrite this using https://github.com/JSQLParser/JSqlParser to get rid of all the Regex code and do proper parsing. But I wasn't really sure how much it was still being used.

You can see the test SQL statements in the repo. Would you mind giving me a test case using a table or stream in those SQL statements?

**Comment by skalinets** [comment]
@stewartbryson thank  you for  the feedback. Could you please point me to the example of test (file in repo) that I could use to provide a test for this case?

**Comment by stewartbryson** [comment]
These are the test SQL scripts that are run duing the testing of the plugin:
https://github.com/RedPillAnalytics/gradle-confluent/tree/master/src/test/resources/src/main/pipeline

If you want to create a PR with just the SQL modified for a test, I can work from that PR. Otherwise, you can include it in the issue.

If you go the PR route, please link the issue in. Thanks!

**Comment by stewartbryson** [comment]
Also @skalinets... if you use `docker compose` with the compose file in the repo, you will get an environment that has all the source topics used to test your SQL.

**Comment by stewartbryson** [comment]
One final thing @skalinets. I believe the README is out of date (I will fix with this PR). `runAllTests` no longer runs docker compose automatically. You need to first:

```
./gradlew composeUp
```

**Comment by stewartbryson** [comment]
@skalinets Can you test and see if release `v1.2.5` solves this issue for you?
If it does, would you close the issue?

**Comment by skalinets** [comment]
@stewartbryson  sure, will test it today. Sorry for delay with response.

**Comment by skalinets** [comment]
it  works fine, thank you!
