### ISSUE TITLE
Update README to reflect the removal of no-create input parameter in pipeline task

### ISSUE THREAD

**Issue by sebrouss** [RedPillAnalytics/gradle-confluent#109]
**Describe the bug**
Documentation is not up to date.
In 1.3.0, --no-create was removed

**Screenshots**
 ./gradlew help --task pipelineExecute
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :help
Detailed task information for pipelineExecute

Path
     :pipelineExecute

Type
     PipelineExecuteTask (com.redpillanalytics.gradle.tasks.PipelineExecuteTask)

Options
     --basic-password     The Password for Basic Authentication with the REST API URL for the KSQL Server. Default: value of 'confluent.pipelinePassword' or ''.

     --basic-username     The Username for Basic Authentication with the REST API URL for the KSQL Server. Default: value of 'confluent.pipelineUsername' or ''.

     --drop-only     When defined, only DROP and TERMINATE statements in KSQL scripts are executed. Used primarily for cleaning existing TABLES/STREAMS and terminating queries.

     --from-beginning     When defined, set 'ksql.streams.auto.offset.reset' to 'earliest'.

     --no-drop     When defined, applicable DROP statements are not auto-generated and executed.

     --no-reverse-drops     When defined, DROP statements are not processed in reverse order of the CREATE statements, which is the default.

     --no-terminate     When defined, applicable TERMINATE statements are not auto-generated and executed.

     --pipeline-dir     The base directory containing SQL scripts to execute, including recursive subdirectories. Default: value of 'confluent.pipelineSourcePath' or 'src/main/pipeline'.

     --rest-url     The REST API URL for the KSQL Server. Default: value of 'confluent.pipelineEndpoint' or 'http://localhost:8088'.

     --statement-pause     The number of seconds to pause execution after a create statement. Default: value of 'confluent.statementPause'.

**Comment by stewartbryson** [comment]
Hey team… traveling today but will work on this ASAP when I return. Thank you! 🙏

**Comment by stewartbryson** [comment]
This was merged.
