### ISSUE TITLE
Ability to set Basic Auth credentials

### ISSUE THREAD

**Issue by Sikta** [RedPillAnalytics/gradle-confluent#76]
**Is your feature request related to a problem? Please describe.**
Infrastructure team is needing to lock down the endpoint with Basic Auth. I don't see a way of supplying credentials currently.

**Describe the solution you'd like**
Along with confluent.pipelineEndpoint allow us to set confluent.pipelineUsername & confluent.pipelinePassword which are then base64 encoded to be sent as an additional header in the requests.

**Comment by stewartbryson** [comment]
Let me take a look at how credentials are managed for the KSQL Server. At the time of initial development, there was no authentication support... it appears that this has changed.

**Comment by Sikta** [comment]
I took a swag at this but don't know groovy and haven't setup any kind of environment where I can run things from.

**Comment by stewartbryson** [comment]
New release will be published in the next few minutes. Please test and let me know. Thanks for the PR!

**Comment by stewartbryson** [comment]
New release: https://plugins.gradle.org/plugin/com.redpillanalytics.gradle-confluent

Configuring with the Gradle `confluent{}` closure: https://s3.amazonaws.com/documentation.redpillanalytics.com/gradle-confluent/1.1.19/index.html

Passing parameters directly to the Gradle tasks:
https://s3.amazonaws.com/documentation.redpillanalytics.com/gradle-confluent/1.1.19/index.html

**Comment by CHR-LeeOlsen** [comment]
I got the following error when I tried using version 1.1.19

```
No signature of method: kong.unirest.StringResponse.header() is applicable for argument types: (String, String) values: [Authorization, Basic 
a3NxbGRldjprc3FsdGVzdDMyMQ==]
  Possible solutions: every(), getHeaders()
```

**Comment by CHR-LeeOlsen** [comment]
I originally had the `If` statement around building the unirest call because I didn't know if calling .header after having called .body() & .asString() would be allowed. I'm thinking we need to change that section  to look like this?

```
      HttpResponse<String> response = Unirest.post("${restUrl}/ksql")
              .header("Content-Type", "application/vnd.ksql.v1+json")
              .header("Cache-Control", "no-cache")
              .header("Postman-Token", "473fbb05-9da1-4020-95c0-f2c60fed8289")


      // streamline the addition of basic credentials slightly
      if (username && password)
         response.header("Authorization", "Basic " + "${username}:${password}".bytes.encodeBase64().toString())

      response.body(JsonOutput.toJson([ksql: prepared, streamsProperties: properties]))
           .asString()
```

**Comment by Sikta** [comment]
It appears the asString() call executes the http call. I lost discovered there is a .basicAuth() method that will do the base64 encoding for us.

``` 
Unirest.get("http://httpbin.org")
            .basicAuth("user", "password1!")
            .asString();

// this adds the header "Authorization: Basic dXNlcjpwYXNzd29yZDEh" 
```

**Comment by stewartbryson** [comment]
@Sikta Can you provide an example of how you configured a specific username and password with your KSQL Server? I need just the most basic so I can enable it in a docker container.

Thanks.

**Comment by CHR-LeeOlsen** [comment]
I'll work to see if I can figure that out locally. Our infrastructure team set it up in our dev environment using https://docs.confluent.io/current/ksql/docs/installation/server-config/security.html#configuring-ksql-for-basic-http-authentication as a guide.

**Comment by stewartbryson** [comment]
Ok @CHR-LeeOlsen. I believe I have corrected the issue. However, I can't test yet, but I know it doesn't break anything, so I will go ahead and publish the new release.

**Comment by CHR-LeeOlsen** [comment]
I'll work to get a true development environment setup for this stuff. Probably going to take me a bit as I'm primarily a .NET developer.

**Comment by stewartbryson** [comment]
I have a docker image with the full Confluent platform on it. I just need to figure out how to easily configure it to require a username and password.

**Comment by stewartbryson** [comment]
https://plugins.gradle.org/plugin/com.redpillanalytics.gradle-confluent

Still not automatically tested... but see if it works for you @CHR-LeeOlsen

**Comment by CHR-LeeOlsen** [comment]
That worked!

Our infrastructure team is creating their own DockerFile.

```
FROM confluentinc/cp-ksql-server:5.2.2
LABEL team="infra"
USER root

RUN mkdir /usr/ksql
RUN mkdir /usr/ext

ADD config/ksql_jaas.config /etc/ksql-server
ADD config/ksql_user_chr.properties /etc/ksql-server

CMD /etc/confluent/docker/run
```

ksql_jaas.config looks like this

```
KsqlServer-Props {
  org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
  file="/etc/ksql-server/ksql_user_chr.properties"
  debug="false";
};
```

ksql_user_chr.properties

```
username: password,admin
```

**Comment by stewartbryson** [comment]
I just want to confirm @CHR-LeeOlsen that the plugin is working with Basic Authentication. Thanks.

**Comment by CHR-LeeOlsen** [comment]
Confirmed! Thanks again for all of your help!

**Comment by stewartbryson** [comment]
Thanks for your contribution!
