### ISSUE TITLE
When using @DeleteTopic under pipelineExecute with a single SQL file, the " DELETE TOPIC" literal is not added to the DELETE TABLE SQL.

### ISSUE THREAD

**Issue by jeffreylutz** [RedPillAnalytics/gradle-confluent#85]
**Describe the bug**
  When using the pipelineExecute (gradle-confluent version 1.1.22) task under gradlew (v 6.4.1) against KSQL under CP 5.5.0, the DELETE TABLE doesn't contain the DELETE TOPIC when the @DeleteTopic annotation comment is added 1 line above the CREATE TABLE string.

**To Reproduce**
1. Go to Unzip attached ZIP file and CD into the project directory
2. Type:  ./gradlew ksql:pipelineExecute   (expecting ksql REST at localhost:8088)
3. Upon success, then type:   ./gradlew ksql:pipelineExecute --no-create -i
4. You will see the string:    DROP TABLE IF EXISTS Q_FORMATION_CAMERA_LOCATIONS;
5.  This string should include " DELETE TOPIC;" at the end...

**Expected behavior**
Expecting the TOPIC backing the table to be deleted due to the @DeleteTopic annotation in the sql.
DROP TABLE IF EXISTS Q_FORMATION_CAMERA_LOCATIONS DELETE TOPIC;
INSTEAD GETTING
DROP TABLE IF EXISTS Q_FORMATION_CAMERA_LOCATIONS;

**Comment by stewartbryson** [comment]
Hey Jeffrey. Can you provide the SQL script? Just paste it in here is fine.

**Comment by stewartbryson** [comment]
Sorry... you mentioned the zip file...

**Comment by stewartbryson** [comment]
Didn't mean to close the issue. I don't see the zip file.

**Comment by stewartbryson** [comment]
@jeffreylutz I'd like to take a look at your issue. I don't see the zip file included here in the issue... do you want to include it?

**Comment by stewartbryson** [comment]
@jeffreylutz I'm going to close this due to lack of response. Please let me know if you are still seeing this issue?
